# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOgPMeRnzSGzX2-cQI_59QrTJ2RBKf8j
"""

students = {
    "S001": {
        "name": "Alice Chen",
        "courses": {
            "CS101": {"grade": 92, "credits": 3},
            "MATH201": {"grade": 88, "credits": 4},
            "AI301": {"grade": 95, "credits": 3},
        },
        "advisor": "Dr. Smith",
    },
    "S002": {
        "name": "Bob Lee",
        "courses": {
            "CS101": {"grade": 85, "credits": 3},
            "MATH201": {"grade": 90, "credits": 4},
        },
        "advisor": "Dr. Patel",
    },
}

alice_ai_grade = students["S001"]["courses"]["AI301"]["grade"]
print("Alice AI301 Grade:", alice_ai_grade)

bob_courses = students["S002"]["courses"]

total_points = 0
total_credits = 0

for course in bob_courses.values():
    total_points += course["grade"] * course["credits"]
    total_credits += course["credits"]

bob_gpa = total_points / total_credits
print("Bob GPA:", bob_gpa)

cs101_students = []

for student in students.values():
    if "CS101" in student["courses"]:
        cs101_students.append(student["name"])

print("Students in CS101:", cs101_students)

all_grades = []

for student in students.values():
    for course in student["courses"].values():
        all_grades.append(course["grade"])

average_grade = sum(all_grades) / len(all_grades)
print("Average Grade:", average_grade)

highest_gpa = 0
top_student = ""

for student in students.values():
    points = 0
    credits = 0
    for course in student["courses"].values():
        points += course["grade"] * course["credits"]
        credits += course["credits"]
    gpa = points / credits

    if gpa > highest_gpa:
        highest_gpa = gpa
        top_student = student["name"]

print("Top Student:", top_student)



import json
from pathlib import Path

config_path = Path("config.json")
results_path = Path("results.json")

with open(config_path, "r") as f:
    config = json.load(f)

print("Training Config:")
for key, value in config.items():
    print(f"{key}: {value}")

results = {
    "model": config.get("model"),
    "epochs": config.get("epochs"),
    "accuracy": 0.92,
    "loss": 0.15,
    "status": "success"
}

with open(results_path, "w") as f:
    json.dump(results, f, indent=4)

print("Results saved to results.json")